# Generated by Django 3.1.5 on 2021-01-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[['Maize', 'MZ'], ['Cocoa', 'CO'], ['Soyabeans', 'SO'], ['Paddy_Rice', 'Ri'], ['Sorghum', 'SG'], ['Ginger', 'Gi']], default='Maize', max_length=12)),
                ('price', models.FloatField(default=170.55)),
            ],
        ),
    ]
